/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package model;


import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Color;
import java.util.Calendar;

public class ExpiryDateCellRenderer extends DefaultTableCellRenderer {

    private static final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

        if (column == 2 && value != null) { // Assuming expiry date is in column 2
            try {
                Date expiryDate = DATE_FORMAT.parse(value.toString());
                Calendar today = Calendar.getInstance();
                Calendar expiry = Calendar.getInstance();
                expiry.setTime(expiryDate);

                today.add(Calendar.DAY_OF_MONTH, 14);

                if (expiry.before(today)) {
                    c.setBackground(Color.RED);
                } else {
                    c.setBackground(Color.WHITE);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            c.setBackground(Color.WHITE);
        }

        return c;
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                


    // Variables declaration - do not modify                     
    // End of variables declaration                   

